version: "3"
services:
    test:
        build:
            context: .
            dockerfile: Dockerfile-test
        depends_on:
            - app
    app:
        build:
            context: ./ucubot
            dockerfile: Dockerfile-test
        ports:
            - "80"
        depends_on:
            - db
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: "1qaz2wsx"
            ACCEPT_EULA: "Y"
